#ifndef COMPILETIMEDIFFERENTIATION_LIBRARY_H
#define COMPILETIMEDIFFERENTIATION_LIBRARY_H


#include <string>

void hello();

constexpr double var_1 = 1 + 2 + 3;

#endif //COMPILETIMEDIFFERENTIATION_LIBRARY_H
